[package]
name = "cita_trie"
version = "0.1.3"
authors = ["yejiayu <yejiayu.fe@gmail.com>"]
description = "Modified Patricia Tree (aka Trie)."
license = "Apache-2.0"
edition = "2018"

[dependencies]
failure = "0.1.5"
bytes = "0.4.11"
rlp = "0.3.0"
tiny-keccak = "*"

[dev-dependencies]
rand = "0.6.3"
hex = "0.3.2"
